
--**********************--
-- INSERT STO_PROCEDURES
--**********************--

-- COUNTRY
CREATE OR REPLACE PROCEDURE ADDNEWCOUNTRY 
(
  ctryName IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO COUNTRY (COUNTRYID, COUNTRYNAME) VALUES(SEQ_COUNTRY.nextVal, ctryName ) ;
END ADDNEWCOUNTRY; 

-- ADDRESS
CREATE OR REPLACE PROCEDURE ADDNEWADDRESS 
(
  STADD IN VARCHAR2 
, CITY IN VARCHAR2 
, COUNTRYID IN NUMBER 
, POSTCODE IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO ADDRESS (ADDRESSID, STREETADDRESS, CITYNAME, COUNTRYID, POSTCODE) VALUES(SEQ_ADDRESS.nextVal, STADD, CITY, COUNTRYID, POSTCODE);
END ADDNEWADDRESS;


-- USERTYPE
CREATE OR REPLACE PROCEDURE ADDNEWUSERTYPE
(
    USRTYPE IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO USERTYPE (USERTYPEID, USERTYPE) VALUES(SEQ_USERTYPE.nextVal, USRTYPE);
END ADDNEWUSERTYPE;


--USERS
CREATE OR REPLACE PROCEDURE ADDNEWUSER
(
    USRNAME IN VARCHAR2,
    USRPASSWORD IN VARCHAR2,
    USRTYPEID IN NUMBER
)AS
BEGIN
    INSERT INTO USERS(USERID, USERNAME, USERPASSWORD, USERTYPEID) VALUES(SEQ_USER.nextVal, USRNAME, USRPASSWORD, USRTYPEID);
END ADDNEWUSER;

--ADMIN
CREATE OR REPLACE PROCEDURE ADDNEWADMIN
(
    USRNAME IN VARCHAR2,
    USRPASSWORD IN VARCHAR2,
    USRTYPEID IN NUMBER,
    ADMNAME IN VARCHAR2
) AS 
BEGIN
  ADDNEWUSER(USRNAME, USRPASSWORD, USRTYPEID);
  INSERT INTO ADMIN(USERID, ADMINNAME) VALUES(SEQ_USER.CURRVAL, ADMNAME);
END ADDNEWADMIN;

--MEMBER
CREATE OR REPLACE PROCEDURE ADDNEWMEMBER
(
    USRNAME IN VARCHAR2,
    USRPASSWORD IN VARCHAR2,
    USRTYPEID IN NUMBER,
    MBRTYPEID IN NUMBER,
    ADDID IN NUMBER,
    MBRNAME IN VARCHAR2,
    MBRPHONENUMBER IN NUMBER,
    MBREMAIL IN VARCHAR2
) AS 
BEGIN
    ADDNEWUSER(USRNAME, USRPASSWORD, USRTYPEID);
    INSERT INTO MEMBER(USERID, MEMBERTYPEID, ADDRESSID, MEMBERNAME, MEMBERPHONENUMBER, MEMBEREMAIL) VALUES(SEQ_USER.CURRVAL, MBRTYPEID, 
        ADDID, MBRNAME, MBRPHONENUMBER, MBREMAIL);
END ADDNEWMEMBER;

--DISCOUNT
CREATE OR REPLACE PROCEDURE ADDNEWDISCOUNT
(
    PERCENTAGE IN NUMBER
) AS
BEGIN 
    INSERT INTO DISCOUNT(DISCOUNTID, DICOUNTPERCENTAGE) VALUES(SEQ_DISCOUNT.NEXTVAL, PERCENTAGE);
END ADDNEWDISCOUNT;


-- DISCOUNTUSAGE
CREATE OR REPLACE PROCEDURE ADDNEWDISCOUNTUSAGE
( 
    PRCHASEID IN NUMBER,
    USRID IN NUMBER,
    TCKTID IN NUMBER
) IS
BEGIN 
    INSERT INTO DISCOUNTUSAGE(PURCHASEID, USERID, TICKETID) VALUES(PRCHASEID, USRID, TCKTID);
END ADDNEWDISCOUNTUSAGE;


-- EVENT
CREATE OR REPLACE PROCEDURE ADDNEWEVENT
(
    LCATIONID IN NUMBER,
    EVNTTYPEID IN NUMBER,
    EVNTNAME IN VARCHAR2,
    EVNTINFORMATION IN VARCHAR2,
    EVNTDATE IN DATE
) AS
BEGIN
    INSERT INTO EVENT(EVENTID, LOCATIONID, EVENTTYPEID, EVENTNAME, EVENTINFORMATION, EVENTDATE) VALUES(SEQ_EVENT.NEXTVAL, LCATIONID
    , EVNTTYPEID, EVNTNAME, EVNTINFORMATION, EVNTDATE);
END ADDNEWEVENT;


--EVENTTYPE
CREATE OR REPLACE PROCEDURE ADDNEWEVENTTYPE
(
    EVNTTYPE IN VARCHAR2
) AS
BEGIN
    INSERT INTO EVENTTYPE(EVENTTYPEID, EVENTTYPE) VALUES(SEQ_EVENTTYPE.NEXTVAL, EVNTTYPE);
END ADDNEWEVENTTYPE;

--GOLDMEMBER
CREATE OR REPLACE PROCEDURE ADDNEWGOLDMEMBER
(
    USRID IN NUMBER,
    DSCOUNTID IN NUMBER
    ) AS
BEGIN
    INSERT INTO GOLDMEMBER(USERID, DISCOUNTID) VALUES(USRID, DSCOUNTID);
END ADDNEWGOLDMEMBER;

--LOCATION
CREATE OR REPLACE PROCEDURE ADDNEWLOCATION
(
    LCATIONTYPEID IN NUMBER,
    ADDID IN NUMBER,
    LCATIONNAME IN VARCHAR2,
    LCATIONINFORMATION IN VARCHAR2
    ) AS
BEGIN
    INSERT INTO LOCATION(LOCATIONID, LOCATIONTYPEID, ADDRESSID, LOCATIONNAME, LOCATIONINFORMATION) VALUES(SEQ_LOCATION.NEXTVAL, LCATIONTYPEID
        , ADDID, LCATIONNAME, LCATIONINFORMATION);
END ADDNEWLOCATION;


--LOCATIONTYPE 
CREATE OR REPLACE PROCEDURE ADDNEWLOCATIONTYPE
(
    LCATIONTYPE IN VARCHAR2    
) AS
BEGIN
    INSERT INTO LOCATIONTYPE(LOCATIONTYPEID, LOCATIONTYPE) VALUES(SEQ_LOCATIONTYPE.NEXTVAL, LCATIONTYPE);
END ADDNEWLOCATIONTYPE;


--MEMBERLOG 
CREATE OR REPLACE PROCEDURE ADDNEWMEMBERLOG
(
    USRID IN NUMBER,
    LGINFORMATION IN VARCHAR2,
    LGDATE IN DATE
) AS
BEGIN
    INSERT INTO MEMBERLOG(LOGID, USERID, LOGINFORMATION, LOGDATE) VALUES(SEQ_MEMBERLOG.NEXTVAL, USRID, LGINFORMATION, LGDATE);
END ADDNEWMEMBERLOG;


--MEMBERTYPE
CREATE OR REPLACE PROCEDURE ADDNEWMEMBERTYPE
(
    MBRTYPE IN VARCHAR2
) AS 
BEGIN
    INSERT INTO MEMBERTYPE(MEMBERTYPEID, MEMBERTYPE) VALUES(SEQ_MEMBERTYPE.NEXTVAL, MBRTYPE);
END ADDNEWMEMBERTYPE;

--PURCHASE

CREATE OR REPLACE PROCEDURE ADDNEWPURCHASE
(
    USRID IN NUMBER,
    TCKTID IN NUMBER
) AS 
BEGIN
    INSERT INTO PURCHASE(PURCHASEID, USERID, TICKETID) VALUES(SEQ_PURCHASE.NEXTVAL, USRID, TCKTID);
END ADDNEWPURCHASE;

--TICKET
CREATE OR REPLACE PROCEDURE ADDNEWTICKET
( 
    EVNTID IN NUMBER,
    TCKTSTATUSID IN NUMBER,
    TCKTPRICE IN NUMBER,
    TCKTSEAT IN VARCHAR2
)AS 
BEGIN
    INSERT INTO TICKET(TICKETID, EVENTID, TICKETSTATUSID, TICKETPRICE, TICKETSEAT) VALUES(SEQ_TICKET.NEXTVAL, EVNTID, TCKTSTATUSID, TCKTPRICE, TCKTSEAT);
END ADDNEWTICKET;

--TICKETSTATUS
CREATE OR REPLACE PROCEDURE ADDNEWTICKETSTATUS
(
    TCKTSTATUS IN VARCHAR2
) AS 
BEGIN
  INSERT INTO TICKETSTATUS(TICKETSTATUSID, TICKETSTATUS) VALUES(SEQ_TICKETSTATUS.NEXTVAL, TCKTSTATUS);
END ADDNEWTICKETSTATUS;

--PROFILEPICTURE
create or replace PROCEDURE ADDNEWPICPATH
(
  USRID IN NUMBER,
  PCPATH IN VARCHAR2
) AS 
BEGIN
UPDATE USERS
SET PICPATH = PCPATH
WHERE USERID = USRID;
END ADDNEWPICPATH;
