create or replace TRIGGER DELETEDISCOUNTUSAGE 
BEFORE DELETE ON PURCHASE
REFERENCING new AS new old AS old
FOR EACH ROW
BEGIN
    DELETE FROM DISCOUNTUSAGE D WHERE :old.PURCHASEID = D.PURCHASEID;
END;