CREATE VIEW GOLMEMBERS AS
select G.USERID, D.DISCOUNTID, D.DICOUNTPERCENTAGE from GOLDMEMBER G INNER JOIN DISCOUNT D 
ON G.DISCOUNTID=D.DISCOUNTID;

CREATE VIEW NORMALMEMBERS AS
select USERID, USERNAME 
from MEMBERS
WHERE USERID IN(
SELECT USERID FROM MEMBERS
MINUS
SELECT USERID FROM GOLDMEMBER
);


CREATE VIEW EVENTDATA AS
SELECT E.EVENTID, E.EVENTNAME, E.EVENTINFORMATION, TO_CHAR(E.EVENTDATE, 'yyyy/mm/dd hh24:mi:ss') EVENTDATE, ET.EVENTTYPE , L.LOCATIONNAME, L.LOCATIONINFORMATION, LT.LOCATIONTYPE, A.STREETADDRESS, A.CITYNAME, C.COUNTRYNAME, A.POSTCODE 
FROM EVENT E 
INNER JOIN LOCATION L
ON E.LOCATIONID=L.LOCATIONID
INNER JOIN EVENTTYPE ET
ON ET.EVENTTYPEID=E.EVENTTYPEID
INNER JOIN ADDRESS A
ON A.ADDRESSID=L.ADDRESSID
INNER JOIN COUNTRY C
ON A.COUNTRYID=C.COUNTRYID
INNER JOIN LOCATIONTYPE LT
ON L.LOCATIONTYPEID=LT.LOCATIONTYPEID;



CREATE VIEW AVAILABLETICKETNUMBER AS
SELECT COUNT(*) AVAILABLETICKETNUMBER , E.EVENTID FROM EVENT E
INNER JOIN TICKET T 
ON T.EVENTID=E.EVENTID 
INNER JOIN TICKETSTATUS TS
ON TS.TICKETSTATUSID=T.TICKETSTATUSID
WHERE TS.TICKETSTATUSID=1
GROUP BY E.EVENTID;




CREATE VIEW TICKETPRICE AS
SELECT T.TICKETPRICE, E.EVENTID FROM EVENT E INNER JOIN TICKET T
ON T.EVENTID=E.EVENTID
WHERE T.TICKETSTATUSID=1;